################## BranchNet Architecture #####################

# The number of least significant bits of PC to use as input
pc_bits: 12

# The width of PC hash to use as input
pc_hash_bits: 12
hash_dir_with_pc: false

# Size of global history used in each chunk
history_lengths: [1000]

# Number of convolution filters in each chunk
conv_filters: [32]

# The width of the convolution filter of each chunk
conv_widths: [7]

# The width of the pooling layer of each chunk
pooling_widths: [0]

# The length of the embedding vector
embedding_dims: 32

# The number of neurons in the hidden fully-connected layers
hidden_neurons: [128, 128]
pruned_hidden_neurons: [0, 0]

# SNN time step
time_step: 8



